### ISSUE TITLE
Emoji has overlap with characters near around

### ISSUE THREAD

**Issue by rebornix** [mjbvz/vscode-markdown-emoji#1]
re https://github.com/Microsoft/vscode/issues/31353

* Install this extension
* Create a new markdown file, type in `:smile:'`
* You'll notice that the smile emoji somehow has overlap with `'` but you don't see this in the webview developer tools

Maybe an issue with chromium rendering.

**Comment by rebornix** [comment]
I saw the same thing in chromium but Edge and Safari are good.

**Comment by mjbvz** [comment]
Here's what I see on Mac with the latest insiders:

<img width="415" alt="screen shot 2017-08-19 at 2 10 38 pm" src="https://user-images.githubusercontent.com/12821956/29490136-3a430676-84e8-11e7-91cb-001fb25fefea.png">


Electron update fixed this I believe
