### ISSUE TITLE
Adding emoji panel

### ISSUE THREAD

**Issue by badetitou** [mjbvz/vscode-markdown-emoji#11]
It would be nice if the extension can add a panel with the existing supported emoji.
I'm thinking about something like in the Latex Workshop extension (see image)

![image](https://user-images.githubusercontent.com/6225039/111979250-1e09fb00-8b05-11eb-91ec-58f17c31a2b8.png)

Thus, it will be easier to add an emoji in the current markdown editor, and one can easily all available emoji from the inside of VSCode.

If you accept PR and believe that this is a good idea, I can try to spend time on this feature request.

**Comment by mjbvz** [comment]
I think that would be a better fix for a separate extension. I could see some people wanting such a panel, but it's a pretty heavy weight thing to add this extension

**Comment by badetitou** [comment]
Ok, thanks for your opinion 😃 
I'll see if I create a separate extension with this feature
