### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [mjbvz/vscode-markdown-emoji#12]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

**Comment by SebTM** [comment]
+1

**Comment by mjbvz** [comment]
Closing as I don't have time to test or publish on other editors and the low usage I've seen for them doesn't seem worth it

**Comment by noraj** [comment]
>  the low usage I've seen for them doesn't seem worth it

Every Linux distro uses FLOSS vscode or vscodium that uses Open VSX, all online version vscode such as https://github.dev, [Github Codespace](https://github.com/features/codespaces), [Gitpod](https://www.gitpod.io/), [Gitlab WebIDE](https://docs.gitlab.com/ee/user/project/web_ide/), etc. all use Open VSX as registry. There is only Microsoft VSCode mostly used on Microsoft Windows that use Microsoft VSCode Marketplace.

**Comment by mjbvz** [comment]
@noraj OpenVsx left, marketplace right:

![Screen Shot 2022-07-15 at 10 22 56 AM](https://user-images.githubusercontent.com/12821956/179276175-e33210a8-be05-4b63-917d-6a24101ea878.png)

0.2% of installs is not compelling

And yes even though I didn't officially publish these,  I do get bugs that only happen in non-vscode editors. I'm not publishing something for platforms I don't test on
