### ISSUE TITLE
Emojis don't render in the preview window inside <table>'s as they do on GitHub.

### ISSUE THREAD

**Issue by MrMattBusby** [mjbvz/vscode-markdown-emoji#16]
Could be by design? This following code does not display the same inside the `<table>` between VS Code and GitHub:

:smile:

<table>
  <thead>
    <tr>
      <th>:smile:</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>:smile:</td>
    </tr>
  </tbody>
</table>

```
<table>
  <thead>
    <tr>
      <th>:smile:</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>:smile:</td>
    </tr>
  </tbody>
</table>
```

<pre>:smile:</pre>

`:smile:`

    :smile:

```
:smile:
```

|:smile:||
|-|-|
|:smile:||

**Comment by kema-dev** [comment]
GitHub renders emojis even inside of HTML elements, and [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji) does it too (you can test [here](https://markdown-it.github.io/). Is it possible add an option to render them inside ? I've never coded an extension but I could try to make a a PR with a little help
