### ISSUE TITLE
VSCode marketplace description has `to ,markdown`

### ISSUE THREAD

**Issue by jsoref** [mjbvz/vscode-markdown-emoji#28]
https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji

<img width="925" alt="image" src="https://github.com/user-attachments/assets/d1a03f31-2cfb-41b3-b25a-be8827435567" />

**Comment by mjbvz** [comment]
Please submit PRs for simple spelling issues like this. Thanks!

**Comment by jsoref** [comment]
@mjbvz: I can't. It isn't present in the codebase. Please stop asking for that!

**Comment by mjbvz** [comment]
Just needs a republish then!

**Comment by jsoref** [comment]
Ah, well, I can't do that either.
