### ISSUE TITLE
[bug]some emoji can't display in my vscode markdown preview

### ISSUE THREAD

**Issue by victorting** [mjbvz/vscode-markdown-emoji#5]
![image](https://user-images.githubusercontent.com/14315278/62758475-1b35d000-bab1-11e9-9383-555b4c9077ce.png)
![image](https://user-images.githubusercontent.com/14315278/62758486-2426a180-bab1-11e9-8957-4c188bb5a2f3.png)
![image](https://user-images.githubusercontent.com/14315278/62758495-2ab51900-bab1-11e9-822f-73d120264810.png)
![image](https://user-images.githubusercontent.com/14315278/62758505-31dc2700-bab1-11e9-8698-de3b60d8511a.png)
![image](https://user-images.githubusercontent.com/14315278/62758522-40c2d980-bab1-11e9-825e-8f2282f598d3.png)
![image](https://user-images.githubusercontent.com/14315278/62758536-4a4c4180-bab1-11e9-8d6f-7f820a820d8d.png)
![image](https://user-images.githubusercontent.com/14315278/62758550-546e4000-bab1-11e9-90ca-de8ea18f1ae9.png)

there is still  a lot of emoji can't display properly, can someone help fix it? thanks!!!

**Comment by FredHappyface** [comment]
Just to follow this up. 

Looks like the flags now have icons 

However there are still a few below that do not. 

`:u6708:` | :u6708: | 
`:u6709:` | :u6709: |   
`:u6307:` | :u6307: | 
`:u5272:` | :u5272: | 
`:u7121:` | :u7121: |   
`:u7981:` | :u7981: | 
`:u7533:` | :u7533: | 
`:u5408:` | :u5408: |  
`:u7a7a:` | :u7a7a: |  
`:u55b6:` |  :u55b6:

`:atom:` | :atom: | 
`:basecamp:` | :basecamp: |  
`:basecampy:` | :basecampy: | 
`:bowtie:` | :bowtie: |   
`:electron:` | :electron: | 
`:feelsgood:` | :feelsgood: |   
`:finnadie:` | :finnadie: | 
`:goberserk:` | :goberserk: |   
`:godmode:` | :godmode: | 
`hurtrealbad:` | :hurtrealbad: |  
`:neckbeard:` | :neckbeard: | 
`:octocat:` | :octocat: |   
`:rage1:` | :rage1: | 
`rage2:` | :rage2: |   
`:rage3:` | :rage3: | 
`rage4:` | :rage4: |   
`:shipit:` | :shipit:  | 
`:suspect:` | :suspect: |   
`:trollface:` | :trollface:


Thanks for a great plugin :smile:

**Comment by FredHappyface** [comment]
I think this is an issue upstream (markdown-it-emoji)

**Comment by victorting** [comment]
> I think this is an issue upstream (markdown-it-emoji)
yes, it is, I found markdown-it-emoji is stopped updating already lasting 4 years

**Comment by vasilii-kovalev** [comment]
`:octocat:` emoji doesn't work...
![image](https://user-images.githubusercontent.com/10310491/87876717-c13cca80-c9e2-11ea-9ccc-fea543da2d01.png)

**Comment by yeyeto2788** [comment]
@mjbvz seems like there was a new commit on the markdown-it-emoji dependency that might fix the issue https://github.com/markdown-it/markdown-it-emoji/commit/339abf72f84a02e66fe9a4d682a7217d1f660e6a that might help on getting the latest emojis from GitHub.

@vasilii-kovalev seems like octocat is not part of the library https://github.com/markdown-it/markdown-it-emoji/blob/master/lib/data/full.json or at least I don't see it.

**Comment by yzy1996** [comment]
About `:octocat:` :octocat:

[see link](https://github.com/markdown-it/markdown-it-emoji/issues/35#issuecomment-487322468)

**Comment by mjbvz** [comment]
Please test the new update, which includes markdown-it-emoji 2.0 . Keep in mind that your operating system must also support displaying the emoji in the first place

Also,  as the other comments we note, we only support standard emoji. `:atom:`, `:octocat:`, and `:shipit:` are GitHub specific. Please open a separate issue if you'd like to see support for those

**Comment by mjbvz** [comment]
Closing based on the above comment. Likely not related to this extension (actual emoji rendering is up to your OS / VS Code)
