### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ronaldorawat** [mjbvz/vscode-markdown-emoji#6]
I tried using :smile but no suggestion is appearing in VS.

**Comment by mjbvz** [comment]
Please provide steps to reproduce

**Comment by wmelton** [comment]
@ronaldorawat I had this problem at first too. VS Code needed to update. I would suggest making sure latest version of VS Code is installed, and then restart. Fixed issue for me.

**Comment by elenalash** [comment]
I can confirm that while the extension doesn't work right after the installation, it works just fine after you restart VS Code. 
Thank you!

**Comment by mjbvz** [comment]
Closing as not actionable without steps to reproduce the problem
