### ISSUE TITLE
Only renders Black and white Emoji

### ISSUE THREAD

**Issue by macizomedia** [mjbvz/vscode-markdown-emoji#9]
Greetings,
My System is Ubuntu 20.04
I do believe that my VSCODE is on the latest version.
Im really confused on which font install so to have the right emoji.

I manage to make the emojis render in the code editor, by adding "Segoe UI Emoji"; I tried by adding also on the Markdown section but I still only get to see Black and White Emojis on the Preview. 

Am I missing something?

many thanks!

**Comment by mjbvz** [comment]
Please share some markdown that demonstrates the issue

This likely is an OS issue (or possibly a font issue). Do these emoji render correctly in other programs?

**Comment by titocru** [comment]
Same issue here

**Comment by mjbvz** [comment]
Closing as likely unrelated to this extension (the actual rendering of emoji is up to VS Code / the OS)
